return {
  "ray-x/go.nvim",
  dependencies = {
    "ray-x/guihua.lua",
    "neovim/nvim-lspconfig",
    "nvim-treesitter/nvim-treesitter",
  },
  config = function()
    require("go").setup({
      disable_defaults = false,
      go = "go",
      goimports = "gopls",
      fillstruct = "gopls",
      gofmt = "gofumpt",
      max_line_len = 120,
      tag_transform = false,
      test_dir = "",
      comment_placeholder = "",
      lsp_cfg = false,
      lsp_gofumpt = true,
      lsp_on_attach = nil,
      lsp_keymaps = false,
      lsp_codelens = true,
      diagnostic = {
        hdlr = false,
        underline = true,
        virtual_text = { spacing = 0, prefix = "■" },
        signs = true,
        update_in_insert = false,
      },
      lsp_document_formatting = true,
      lsp_inlay_hints = {
        enable = true,
        only_current_line = false,
        only_current_line_autocmd = "CursorHold",
        show_variable_name = true,
        parameter_hints_prefix = "󰊕 ",
        show_parameter_hints = true,
        other_hints_prefix = "=> ",
        max_len_align = false,
        max_len_align_padding = 1,
        right_align = false,
        right_align_padding = 6,
        highlight = "Comment",
      },
      gopls_cmd = nil,
      gopls_remote_auto = true,
      dap_debug = false,
      dap_debug_keymap = false,
      dap_debug_gui = false,
      dap_debug_vt = false,
      build_tags = "",
      textobjects = true,
      test_runner = "go",
      verbose_tests = true,
      run_in_floaterm = false,
      trouble = false,
      test_efm = false,
      luasnip = false,
      icons = { breakpoint = "🧘", currentpos = "🏃" },
    })

    local format_sync_grp = vim.api.nvim_create_augroup("GoFormat", {})
    vim.api.nvim_create_autocmd("BufWritePre", {
      pattern = "*.go",
      callback = function()
        require("go.format").goimports()
      end,
      group = format_sync_grp,
    })
  end,
  event = { "CmdlineEnter" },
  ft = { "go", "gomod" },
  build = ':lua require("go.install").update_all_sync()',
}
